[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.6.0"
borsh-derive = "1.6.0"
solana-program = "4.0.0"

[dev-dependencies]
solana-program-test = "3.1.9"
solana-sdk = "4.0.1"
